config/routes.rb
MfgOrderx::Engine.routes.draw do
  resources :orders do
    collection do
      get :search
      get :search_results
      get :stats
      get :stats_results
    end
  end

  root :to => 'orders#index'
end

app/models/mfg_orderx/order.rb
module MfgOrderx
  class Order < ActiveRecord::Base
    attr_accessor :product_info, :customer_name, :expedite_noupdate, :cancelled_noupdate, :completed_noupdate, :sample_required_noupdate, :quote_id_noupdate, 
                  :quote_unit_price, :order_total, :order_wt, :unit_price, :product_wt, :id_noupdate, :wf_comment
    attr_accessible :cancelled, :completed, :customer_po, :delivery_date, :expedite, :last_updated_by_id, :order_date, :order_requirement, :qty, 
                    :quote_id, :sample_required, :shipping_date, :contract_required, :executioner_id, :rfq_id, :drawing_num, :wf_state,
                    :product_info, :customer_name, :quote_id_noupdate, :quote_unit_price, :order_total, :order_wt, :unit_price, :product_wt,
                    :as => :role_new
    attr_accessible :cancelled, :completed, :customer_po, :delivery_date, :expedite, :last_updated_by_id, :order_date, :order_requirement, :qty, 
                    :sample_required, :shipping_date, :contract_required, :executioner_id, :drawing_num, :wf_state,
                    :product_info, :customer_name, :expedite_noupdate, :cancelled_noupdate, :completed_noupdate, :sample_required_noupdate, :quote_id_noupdate, 
                    :quote_unit_price, :order_total, :order_wt, :unit_price, :product_wt, :id_noupdate, :wf_comment,
                    :as => :role_update
                    
    attr_accessor :customer_id_s, :start_date_s, :end_date_s, :time_frame_s, :drawing_num_s, :delivery_date_s, :rfq_id_s, :completed_s, :id_s, 
                  :cancelled_s, :order_date_s, :shipping_date_s
    attr_accessible :customer_id_s, :start_date_s, :end_date_s, :time_frame_s, :drawing_num_s, :delivery_date_s, :rfq_id_s, :completed_s, :id_s, 
                    :cancelled_s,  :order_date_s, :shipping_date_s,
                    :as => :role_search_stats                
    
    belongs_to :last_updated_by, :class_name => 'Authentify::User'
    belongs_to :executioner, :class_name => 'Authentify::User' 
    belongs_to :rfq, :class_name => MfgOrderx.rfq_class.to_s
    belongs_to :quote, :class_name => MfgOrderx.quote_class.to_s
    
    validates :quote_id, :rfq_id, :presence => true,
                         :numericality => {:greater_than => 0}
    validates :qty, :presence => true,
                    :numericality => {:greater_than => 0, :message => I18n.t('Qty > 0')}                     
    validates :order_date, :drawing_num, :presence => true
    validate :dynamic_validate 
    
    validate :validate_wf_input_data, :if => 'wf_state.present?' 
       
    def dynamic_validate
      wf = Authentify::AuthentifyUtility.find_config_const('dynamic_validate', 'mfg_orderx')
      eval(wf) if wf.present?
    end
  end
end

app/controllers/mfg_orderx/application_controller.rb
module MfgOrderx
  class ApplicationController < ApplicationController
    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
    include Authentify::UserPrivilegeHelper
    include Commonx::CommonxHelper
    include Searchx::SearchHelper
    
    before_filter :require_signin
    before_filter :max_pagination
    before_filter :check_access_right 
    before_filter :load_session_variable, :only => [:new, :edit]  #for parent_record_id & parent_resource in check_access_right
    after_filter :delete_session_variable, :only => [:create, :update]  #for parent_record_id & parent_resource in check_access_right
    before_filter :view_in_config?
    
    protected
  
    def max_pagination
      @max_pagination = find_config_const('pagination').to_i
    end
    
    def view_in_config?
      @view_in_config = Authentify::AuthentifyUtility.load_view_in_config
    end
    
    #engine's
    def return_customers_by_access_right     
      access_rights, model_ar_r, has_record_access = access_right_finder('index', MfgOrderx.customer_class.to_s.underscore.pluralize)
      return [] if access_rights.blank?
      return model_ar_r #instance_eval(access_rights.sql_code) #.present?
    end
  end
end

app/controllers/mfg_orderx/orders_controller.rb
require_dependency "mfg_orderx/application_controller"

module MfgOrderx
    
  class OrdersController < ApplicationController
    before_filter :require_employee
    before_filter :load_parent_record
    
    def index
      @title = t('Orders')
      @orders = params[:mfg_orderx_orders][:model_ar_r]
      @orders = @orders.where(:rfq_id => @rfq.id) if @rfq
      @orders = @orders.where(:quote_id => @quote.id) if @quote
      @orders = @orders.page(params[:page]).per_page(@max_pagination)
      @erb_code = find_config_const('order_index_view', 'mfg_orderx')
    end
  
    def new
      @title = t('New Order')
      @order = MfgOrderx::Order.new()
      @erb_code = find_config_const('order_new_view', 'mfg_orderx')
    end
  
    def create
      @order = MfgOrderx::Order.new(params[:order], :as => :role_new)
      @order.last_updated_by_id = session[:user_id]
      if @order.save
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Saved!")
      else
        @rfq = MfgOrderx.rfq_class.find_by_id(params[:order][:rfq_id]) if params[:order].present? && params[:order][:rfq_id].present?
        @quote = MfgOrderx.quote_class.find_by_id(params[:order][:quote_id]) if params[:order].present? && params[:order][:quote_id].present?
        @erb_code = find_config_const('order_new_view', 'mfg_orderx')
        flash[:notice] = t('Data Error. Not Saved!')
        render 'new'
      end
    end
  
    def edit
      @title = t('Update Order')
      @order = MfgOrderx::Order.find_by_id(params[:id])
      @erb_code = find_config_const('order_edit_view', 'mfg_orderx')
    end
  
    def update
      @order = MfgOrderx::Order.find_by_id(params[:id])
      @order.last_updated_by_id = session[:user_id]
      if @order.update_attributes(params[:order], :as => :role_update)
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Updated!")
      else
        @erb_code = find_config_const('order_edit_view', 'mfg_orderx')
        flash[:notice] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end
  
    def show
      @title = t('Order Info')
      @order = MfgOrderx::Order.find_by_id(params[:id])
      @erb_code = find_config_const('order_show_view', 'mfg_orderx')
    end
    
    protected
    def load_parent_record
      @rfq = MfgOrderx.rfq_class.find_by_id(params[:rfq_id]) if params[:rfq_id].present?
      @rfq = MfgOrderx.rfq_class.find_by_id(MfgOrderx.quote_class.find_by_id(params[:quote_id]).rfq_id) if params[:quote_id].present?
      @quote = MfgOrderx.quote_class.find_by_id(params[:quote_id]) if params[:quote_id].present?
      @rfq = MfgOrderx.rfq_class.find_by_id(MfgOrderx::Order.find_by_id(params[:id]).rfq_id) if params[:id].present?
      @quote = MfgOrderx.quote_class.find_by_id(MfgOrderx::Order.find_by_id(params[:id]).quote_id) if params[:id].present?
    end
  end
end

app/helpers/mfg_orderx/application_helper.rb
module MfgOrderx
  module ApplicationHelper
  end
end

app/helpers/mfg_orderx/orders_helper.rb
module MfgOrderx
  module OrdersHelper
  end
end

app/views/mfg_orderx/orders/_form.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
<% else %>
<%= simple_form_for @order do |f| %>    

  <%= f.input :quote_id_noupdate, :label => t("Quote#"), :readonly => true, :input_html => {:value => @quote.id} %> 
  <%= f.input :customer_name, :label => t('Customer'), :readonly => true, :input_html => {:value => @rfq.customer.name} %>
  <%= f.input :product_info, :label => t("Product Name"), :readonly => true, :input_html => {:value => @rfq.product_name }  %> 
  <%= f.input :drawing_num, :label => t("Drawing#"), :readonly => readonly?(@order, 'drawing_num')  %> 
  <%= f.input :unit_price, :label => t("Unit Price"), :readonly => true, :input_html => {:value => @quote.unit_price}%> 
  <%= f.input :product_wt, :label => t("Product WT(g)"), :readonly => true, :input_html => {:value => @rfq.product_wt}%>  
  <%= f.input :order_date, :label => t("Order Date"), :as => :string %> 
  <%= f.input :qty, :label => t("Qty") %> 
  <%= f.input :order_total, :label => t("Order Total($)"), :readonly => true %> 
  <%= f.input :order_wt, :label => t("Order WT(kg)"), :readonly => true %>
  <%= f.input :order_requirement, :label => t("Order Requirement"), :input_html => {:rows => 4} %> 
  <%= f.input :customer_po, :label => t("PO#") %> 
  <%= f.input :delivery_date, :label => t("Delivery Date"), :as => :string %> 
  <%= f.input :shipping_date, :label => t("Shipping Date"), :as => :string %>   
  <% if readonly?(@order, 'expedite')%>
     <%= f.input :expedite_noupdate, :label => t('Expedite'), :readonly => true, :required => false, :input_html => {:value => @order.expedite} %>
  <% else %>
     <%= f.input :expedite, :label => t('Expedite'), :as => :boolean %>
  <% end %>
  <% if readonly?(@order, 'cancelled')%>
     <%= f.input :cancelled_noupdate, :label => t('Cancelled'), :readonly => true, :required => false, :input_html => {:value => @order.cancelled} %>
  <% else %>
     <%= f.input :cancelled, :label => t('Cancelled'), :as => :boolean %>
  <% end %>
  <% if readonly?(@order, 'sample_required')%>
     <%= f.input :sample_required_noupdate, :label => t('Require Sample?'), :readonly => true, :required => false, :input_html => {:value => @order.sample_required} %>
  <% else %>
     <%= f.input :sample_required, :label => t("Require Sample?"), :as => :boolean %> 
  <% end %>
  <% if readonly?(@order, 'completed')%>
     <%= f.input :completed_noupdate, :label => t('Completed'), :readonly => true, :required => false, :input_html => {:value => @order.completed} %>
  <% else %>
     <%= f.input :completed, :label => t('Completed'), :as => :boolean %>
  <% end %>
  <%#= f.input :executioner_id, :collection => Authentify::UsersHelper::return_users('sales', params[:controller]), :label => t("Executioner"),:label_method => :name, :value_method => :id, :include_blank => true %>
  
  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save') %>  
<% end %>

<% end %>

app/views/mfg_orderx/orders/_form_list.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
<% else %>
<div class="pagination"><%= will_paginate models %></div>
    <table class="table table-striped">
		<tr>
			<th>#</th>
			<th><%= t('Order Date') %></th>
			<th><%= t('Customer') %></th>
			<th><%= t('Product Name') %></th>
			<th><%= t('Drawing#') %></th>
			<th><%= t('Qty') %></th>	
			<th><%= t('Delivery Date') %></th>
			<th><%= t('Shipping Date') %></th>			
			<th><%= t('Completed?') %></th>
			<th><%= t('Sample?') %></th>
			<th><%= t('Last Updated By') %></th>
			<th></th>
			<th></th>
			
		</tr>
		<% models.each do |r| %>
		  <tr>
		  	<% unless has_action_right?('show', params[:controller], r) %>
		  	  <td><%= prt(r, :id) %></td>
		  	<% else %>
		  	  <td><%= link_to r.id.to_s, SUBURI + "/authentify/view_handler?index=1&url=#{order_path(r)}" %></td>
		  	<% end %>
		  	<td><%= r.order_date.strftime("%Y/%m/%d") %></td>
		  	<td><%= MfgOrderx.rfq_class.find_by_id(r.rfq_id).customer.name %></td>
		  	<% rfq = MfgOrderx.rfq_class.find_by_id(r.rfq_id) %>
		  	<% if has_action_right?('show', MfgOrderx.rfq_class.to_s.underscore.pluralize, rfq) %>
			  <td><%= link_to rfq.product_name + ' ' + rfq.drawing_num, SUBURI + "/authentify/view_handler?index=1&url=#{SUBURI + CGI::escape(eval(MfgOrderx.show_rfq_path))}" %></td>
			<% else %>
			  <td><%= rfq.product_name %></td>
			<% end %>
			<td><%= prt(r, :drawing_num) %></td>
			<td><%= prt(r, :qty) %></td>
			<td><%= r.delivery_date.strftime("%Y/%m/%d") %></td>
			<td><%= r.shipping_date.strftime("%Y/%m/%d") %></td> 
			<td><%= r.completed ? t('Yes') : t('No') %></td>
			<td><%= r.sample_required ? t('Yes') : t('No') %></td>
			<td><%= prt(r, 'last_updated_by.name') %></td>    
			<td><%= link_to t('Samples'), SUBURI + "/authentify/view_handler?index=1&url=#{SUBURI + CGI::escape(eval(MfgOrderx.sample_index_path))}", :class => BUTTONS_CLS['action'] %></td>
			<td><%= link_to t('Edit'), SUBURI + "/authentify/view_handler?index=1&url=#{edit_order_path(r)}", :class => BUTTONS_CLS['action']  if has_action_right?('update', params[:controller], r) %></td>
			
		  </tr>
		<% end %>
	</table>
	
	<table class="table table-striped">
	  <tr>
	    <th>
	    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	    	<%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action']  %>
	    	<%= link_to t('New Order'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI::escape new_order_path(:quote_id => @quote.id, :parent_record_id => @quote.id, :parent_resource => MfgOrderx.quote_class.to_s.underscore.pluralize) }", :class => BUTTONS_CLS['action']  if @quote && has_action_right?('create', params[:controller], @quote) %>
	    </th>
	  </tr>
	</table>

<% end %>	

app/views/mfg_orderx/orders/_form_new.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
<% else %>
<%= simple_form_for @order do |f| %>    

  <%= f.input :quote_id, :label => t("Quote#"), :readonly => true, :input_html => {:value => @quote.id} %> 
  <%= f.input :customer_name, :label => t('Customer'), :readonly => true, :input_html => {:value => @rfq.customer.name} %>
  <%= f.input :rfq_id, :as => :hidden, :input_html => {:value => @rfq.id} %>
  <%= f.input :product_info, :label => t("Product Name"), :readonly => true, :input_html => {:value => @rfq.product_name }  %> 
  <%= f.input :drawing_num, :label => t("Drawing#"), :input_html => {:value => @rfq.drawing_num}  %> 
  <%= f.input :unit_price, :label => t("Unit Price($)"), :readonly => true, :input_html => {:value => @quote.try(:unit_price)} %> 
  <%= f.input :product_wt, :label => t("Product WT(g)"), :readonly => true, :input_html => {:value => @rfq.try(:product_wt)} %>
  <%= f.input :order_date, :label => t("Order Date"), :as => :string %> 
  <%= f.input :qty, :label => t("Qty") %>
  <%= f.input :order_total, :label => t("Order Total($)"), :readonly => true %> 
  <%= f.input :order_wt, :label => t("Order WT(kg)"), :readonly => true %>
  <%= f.input :order_requirement, :label => t("Order Requirement"), :input_html => {:rows => 4} %> 
  <%= f.input :customer_po, :label => t("PO#") %> 
  <%= f.input :delivery_date, :label => t("Delivery Date"), :as => :string %> 
  <%= f.input :shipping_date, :label => t("Shipping Date"), :as => :string %> 
  <%= f.input :expedite, :label => t('Expedite'), :as => :boolean %>
  <%= f.input :sample_required, :label => t("Require Sample?"), :as => :boolean %> 
  <%#= f.input :executioner_id, :collection => Authentify::UsersHelper::return_users('sales', params[:controller]), :label => t("Executioner"),:label_method => :name, :value_method => :id, :include_blank => true %>
  
  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save') %>  
<% end %>

<% end %>

app/views/mfg_orderx/orders/create.html.erb
<h1>Rfqs#create</h1>
<p>Find me in app/views/jobshop_rfqx/rfqs/create.html.erb</p>

app/views/mfg_orderx/orders/edit.html.erb
<div id="main_body">
<h4><%=t('Edit Order') %></h4>
 
<%= render 'form'  %>
 
</div>
  
 

app/views/mfg_orderx/orders/index.html.erb
<div id="main_body">
	<h4><%=t('Orders') %></h>
 
	<%= render partial: 'form_list', locals: {models: @orders} %>
 
</div>

app/views/mfg_orderx/orders/new.html.erb
<div id="main_body">
<h4><%=t('New Order') %></h4>

<%= render 'form_new' %>

</div>

app/views/mfg_orderx/orders/show.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
<% else %>
<div id="main_body">
<h4><%=t('Order Info') %></h4>

<p>
  <b><%= t('Customer') %></b>
  <%= @rfq.customer.name %>
</p>
<p>
  <b><%= t('Product Name') %></b>
  <%= @rfq.product_name %>
</p>
<p>
  <b><%= t('Drawing#') %></b>
  <%= @order.drawing_num %>
</p>
<p>
  <b><%= t('Quote#') %></b>
  <%= @order.quote_id %>
</p>
<p>
  <b><%= t('Unit Price') %></b>
  <%= @order.quote.unit_price %>
</p>
<p>
  <b><%= t('Order Date') %></b>
  <%= @order.order_date.strftime("%Y/%m/%d") %>
</p>

<p>
  <b><%= t('Order Requirement') %></b>
  <%= @order.order_requirement %>
</p>
<p>
  <b><%= t('Qty')  %></b>
  <%= @order.qty %>
</p>
<p>
  <b><%= t('Order Total')  %></b>
  <%= number_with_precision(@order.qty * @order.quote.unit_price, :precision => 2) %>
</p>
<p>
  <b><%= t('Order WT(kg)')  %></b>
  <%= number_with_precision(@order.qty * @rfq.product_wt/1000.00, :precision => 2) %>
</p>
<p>
  <b><%= t('Delivery Date') %></b>
  <%= @order.delivery_date.strftime("%Y/%m/%d") %>
</p>
<p>
  <b><%= t('Shipping Date') %></b>
  <%= @order.shipping_date.strftime("%Y/%m/%d") if @order.shipping_date.present? %>
</p>

<p>
  <b><%= t('Cancelled') %></b>
  <%= @order.cancelled ? t('Yes') : t('No') %>
</p>
<p>
  <b><%= t('Expedite') %></b>
  <%= @order.expedite ? t('Yes') : t('No') %>
</p>
<p>
  <b><%= t('Completed') %></b>
  <%= @order.completed ? t('Yes') : t('No') %>
</p>
<p>
  <b><%= t('Sample Required?') %></b>
  <%= @order.sample_required ? t('Yes') : t('No') %>
</p>
<p>
  <b><%= t('Executioner') %></b>
  <%= @order.executioner.name if @order.executioner_id.present? %>
</p>
<p>
  <b><%= t('Last Updated By') %></b>
  <%= @order.last_updated_by.name %>
</p>
<p>
  <b>LOG：</b>
  <% Commonx::Log.where('resource_id = ? AND resource_name = ?', @order.id, params[:controller].sub('/', '_')).order("created_at DESC").each do |t| %>
    <li><%= t.created_at.strftime("%Y/%m/%d") %>,&nbsp; <%= t.last_updated_by.name %>,&nbsp; <%= t.log %> </li>
  <% end %>
</p>

	<table class="table table-striped">
	  <tr>
	    <th>
  			<%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :id => 'close', :class => BUTTONS_CLS['action'] %>
  			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<%= link_to t('New Log'), SUBURI + commonx.new_log_path(:resource_id => @order.id, :resource_name => params[:controller], :subaction => 'order', :format => :js), :remote => true, 
                          :id => 'new_log_link', :class => BUTTONS_CLS['action'] if has_action_right?('create_order', 'commonx/logs') %>
          </th>
	  </tr>
	</table>     	
</div>

<% end %>

app/views/mfg_orderx/orders/update.html.erb
<h1>Rfqs#update</h1>
<p>Find me in app/views/jobshop_rfqx/rfqs/update.html.erb</p>